### ISSUE TITLE
[CRITICAL] Items not removed from inventory when players sell them all

### ISSUE THREAD

**Issue by amadeusmz** [Majncraft/BetterShops#3]
This is the log when this issue occured, but in the code, the plugin will save transaction AFTER removing items from player's inventory.
I can't replicate this, but somehow the players can abuse this and leads to money bug.
https://pastebin.com/huazAXJC

**Comment by dwi** [comment]
Switched the order in commit https://github.com/Majncraft/BetterShops/commit/1b8be97446846831d422c7ee909b28ae6b282976
