### ISSUE TITLE
Some error in ver 1.12 and suggestions

### ISSUE THREAD

**Issue by EnityStaller** [Majncraft/BetterShops#6]
Does not work with 1.12.2. GUI's are closed when they are opened, and creating the shop does nothing as the GUI for the shop doesn't open.
I upload your plugins in this link
Link: https://www.spigotmc.org/resources/bettershops-recode.47533/
If you plan to add new features, here are some suggestions.
- Creative mode protection. (Players actually can open shops in creative mode and can sell any item.)
- GUI with list of all shops (player heads) and click on head player to open shop directly.

**Comment by dwi** [comment]
1.12.2 compatibility fixed
